on:
  push:
    branches-ignore:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  validate-ps51:
    if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install Prerequisites (PowerShell 5.1)
        run: .\build\prerequisites.ps1
        shell: powershell
      - name: Validate (PowerShell 5.1)
        run: .\build\validate.ps1
        shell: powershell

  validate-ps7:
    if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install Prerequisites (PowerShell 7)
        run: .\build\prerequisites.ps1
        shell: pwsh
      - name: Validate (PowerShell 7)
        run: .\build\validate.ps1
        shell: pwsh
